services:
  bike-api:
    build: ./src/api
    ports:
      - "8080:8080"
    restart: always
  evaluation:
    build: ./src/evaluation
    depends_on:
      - bike-api

    prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      -  ./deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deployment/prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
      # C'est sur ce port que Prometheus viendra "scraper" les métriques système.
    volumes:
      - /proc:/host/proc:ro
      # Le répertoire '/proc' contient des informations vitales sur l'état du noyau Linux et des processus en cours (utilisation CPU par process, infos mémoire, etc.).
      - /sys:/host/sys:ro
      # Le répertoire '/sys' expose des informations sur les périphériques matériels et les configurations du noyau.
      - /:/rootfs:ro
      # C'est essentiel pour que Node Exporter puisse accéder aux informations sur l'utilisation de l'espace disque de l'hôte.
    command:
    # Ces commandes indiquent à Node Exporter où trouver les systèmes de fichiers de l'hôte que nous venons de monter via les volumes.
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/run/docker/netns/.+)$'
    restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}