global:
  scrape_interval: 15s # Frequence a laquelle Prometheus va scrapper les métriques
  evaluation_interval: 15s # Fréquence à laquelle Prometheus va évaluer les règles d'alerte

  # Indique à Prometheus où trouver les fichiers de règles d'alerte
rule_files:
  - "rules/*.yml" # Charge tous les fichiers .yml dans le sous-répertoire 'rules'

scrape_configs:
  - job_name: 'prometheus' # Nom du job pour identifier les métriques scrappées
    static_configs:
      - targets: ['localhost:9090'] # Adresse du service à scrapper
  - job_name: 'bike_api'
    static_configs:
      - targets: ['bike-api:8080'] # Adresse du service à scrapper
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']